main: com.westosia.TradingPlugin.Main
name: TradingPlugin
version: ${project.version}
api-version: 1.13
author: Jamie Cee
description: A trading plugin to allow 2 players to trade items with one another.
